FROM debian:9

RUN apt-get update -qq && \
    apt-get install -qq sudo python3-apt python3-pycurl python3-pip python3-dev \
                        python3-passlib libffi-dev && \
    pip3 install -U setuptools paramiko && \
    pip3 install -q ansible==2.7.10

    WORKDIR /tmp/ansible-role-3proxy
    COPY  .  /tmp/ansible-role-3proxy

    RUN echo "localhost ansible_python_interpreter=/usr/bin/python3" > inventory
    RUN ansible-playbook -i inventory -c local tests/playbook.yml --syntax-check
    RUN ansible-playbook -i inventory -c local tests/playbook.yml
